// valgrind --leak-check=full --show-leak-kinds=all --track-fds=yes
// ./pipex infile.txt "/bin/ls" "/bin/cat" outfile.txt

/* COMMENT TRAITER CETTE LIGNE

	./pipex infile.txt "/bin/ls" "/bin/cat" outfile.txt

	ON RECUPRERE LA LIGNE 
	SI ARGC != 5)
		ERREUR
	PARSING : 

		ON TRAITE LA CHAINE DE CARACTERES (argv[1 a 4])
		{
			ON CONSIDERE ARGV[1] = INFILE 
			{
				arguments->fd_infile = open(ARGV1)
				SI MAUVAISE INFILE -> ON QUITTE ET ON SORT 1
				soit on redirige vers l'entree standard
			}
			ON CONSIDERE ARGV[4] = OUTFILE 
			{
				arguments->fd_outfile = open(ARGV[4])
				SI ERREUR POUR OUTFILE -> ON QUITTE ET ON RESSORT 2 
				soit on redirige vers la sortie standard
			}

			ON CONSIDERE ARGV[2] = CMD1
			{
				SI (ARGV[2] CONTIENT LE PATH ENTIER (USR/BIN/LS))
					CMD[1][0] = USR/BIN/LS || PATH = USR/BIN/LS
					CMD[1][i] = CONTENU SPLIT
				SINON
					ON RECUPRE PATH;
					ON SPLIT EN FONCTION DES :
					ON TESTE POUR CHAQUE SPLIT[i]
					SI access(F_OK)
						CMD[1][0] = SPLIT[i] + CMD
			}
			ON CONSIDERE ARGV[3] = CMD2
			{
				SI (ARGV[2] CONTIENT LE PATH ENTIER (USR/BIN/LS))
						CMD[1][0] = USR/BIN/LS || PATH = USR/BIN/LS
						CMD[1][i] = CONTENU SPLIT
				SINON
					ON RECUPRE PATH;
					ON SPLIT EN FONCTION DES :
					ON TESTE POUR CHAQUE SPLIT[i]
					SI access(F_OK)
						CMD[1][0] = SPLIT[i] + CMD
			}
		}

	EXECUTION

		INITIALISER UN TABLEAU DE PID = pid[2]
		CREER UNE PREMIERE FORK

			FORMATER CHILD EN FONCTION DE SA POSITION (1ER OU 2EME)

			GERER LES REDIRECTIONS

				INITALISER IN_FD ET OUT_FD

				AFFECTER A  IN_FD -> INFILE_FD SI 1ER CHILD
				AFFECTER A  OUT_FD -> PIPE[0] SI 1ER CHILD

			SI ERREUR (IN_FD < 0 OU OUT_FD < 0)
				ERREUR (FREE ET EXIT) /!\ ON EST TOUJOUR DANS UN CHILD
			DUP2(INFILEFD, STDIN)
			DUP2(OUTFILEFD, STDOUT)
			FERMER TOUT LE RESTE

			CREER L'EXECUTIION

				FAIRE PASSER  DANS EXECVE
				GERER LES CAS D'ERREURS OU EXECVE ECHOUE

		CREER UNE DEUXIEME FORK

			FORMATER CHILD EN FONCTION DE SA POSITION (1ER OU 2EME)

				GERER LES REDIRECTIONS

				INITALISER IN_FD ET OUT_FD

				AFFECTER A  IN_FD -> PIPE[1] SI 2EME CHILD
				AFFECTER A  OUT_FD -> OUTFILE_FD SI 2EME CHILD

			SI ERREUR (IN_FD < 0 OU OUT_FD < 0)
				ERREUR (FREE ET EXIT) /!\ ON EST TOUJOUR DANS UN CHILD
			DUP2(INFILEFD, STDIN)
			DUP2(OUTFILEFD, STDOUT)
			FERMER TOUT LE RESTE

			CREER L'EXECUTIION

				FAIRE PASSER  DANS EXECVE
				GERER LES CAS D'ERREURS OU EXECVE ECHOUE

	PENDANT CE TEMPS LA DANS LE PARENT :

		ON COMMENCE PAR TOUT FERMER
		ON ATT POUR LES 2 PROCESSUS DE SE TERMINER
		ON AFFECTE A STATUS LA VALEUR DE RETOUR DE LA DERNIERE COMMANDE RECU PAR WAITPID
		ON RETURN
*/